### ISSUE TITLE
Wrong guide being highlighted

### ISSUE THREAD

**Issue by dk0r** [harai/indent-guide-improved#46] opened 2016-07-28 15:12 UTC
When my cursor is on line-25 (see image below), `this` ident guide (associated with lines 14-26) is highlighted. I expect the ident guide associated w/ lines 15-25 to be highlighted when my cursor is on line-25.
http://i.imgur.com/96wWmXY.png

**Comment by harai** [comment] 2016-08-06 03:28
Duplicate of #41.

**Closed by harai** 2016-08-06 03:28 UTC
Labels: duplicate
