### ISSUE TITLE
Failed to activate the indent-guide-improved package on atom 1.9.0

### ISSUE THREAD

**Issue by ra100** [harai/indent-guide-improved#42] opened 2016-05-18 09:34 UTC
Doesn't work on Atom 1.9.0, they have removed editor.displayBuffer, so the method which needs rows fails. TokenizedBuffer is used instead. I haven't found simple solution to fix this.

**Atom Version**: 1.9.0-dev-346d998
**System**: Ubuntu 16.04
**Thrown From**: [indent-guide-improved](https://github.com/harai/indent-guide-improved) package, v1.4.8

### Stack Trace

Failed to activate the indent-guide-improved package

```
At Cannot read property 'getRegions' of undefined

TypeError: Cannot read property 'getRegions' of undefined
    at updateGuide (/home/ra100/.atom/packages/indent-guide-improved/lib/indent-guide-improved.coffee:33:54)
    at /home/ra100/.atom/packages/indent-guide-improved/lib/indent-guide-improved.coffee:87:7
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:309:9)
    at Object.module.exports.activate (/home/ra100/.atom/packages/indent-guide-improved/lib/indent-guide-improved.coffee:82:20)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:29
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:215:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by Stanzilla** [comment] 2016-06-09 09:53
Yup, same here

**Comment by github-polymer-user** [comment] 2016-06-09 13:08
same

**Comment by harai** [comment] 2016-06-11 05:22
Fixed by #43 .
Thank you @ra100 !

**Closed by harai** 2016-06-11 05:22 UTC

**Comment by michaelaye** [comment] 2017-08-09 05:30
Reappeared for Atom 1.19.0, but fixed by subsequent update.

**Comment by enricopesce** [comment] 2017-08-10 08:01
same error!

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [indent-guide-improved](https://github.com/harai/indent-guide-improved) package 1.4.12


### Stack Trace

Failed to activate the indent-guide-improved package

```
At Invalid Point: (NaN, 0)

TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at DisplayLayer.translateScreenPosition (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:333:17)
    at DisplayLayer.clipScreenPosition (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:391:18)
    at TextEditor.module.exports.TextEditor.clipScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1793:38)
    at HTMLElement.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:242:38)
    at updateGuide (/packages/indent-guide-improved/lib/indent-guide-improved.coffee:17:36)
    at /packages/indent-guide-improved/lib/indent-guide-improved.coffee:79:7
    at Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:717:15)
    at Object.activate (/packages/indent-guide-improved/lib/indent-guide-improved.coffee:74:20)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
indent-guide-improved 1.4.12 
language-docker 1.1.8 
markdown-preview-plus 2.4.10 
platformio-ide-terminal 2.5.3 
split-diff 1.4.3 
```

**Comment by joldnl** [comment] 2017-08-14 19:50
Seems to be fixed with the latest releases of atom and Indent Guide Improved (on osx).

**Comment by ipcross** [comment] 2017-09-26 07:36
+1 same bug.
Atom: 1.20.1 x64

**Comment by DavidKopecky** [comment] 2018-01-04 00:55
Hitting this with 1.23.2 x64
